AWSTemplateFormatVersion: 2010-09-09
Resources:
  S3BucketDataSet:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: tech-challenge-bucket
      LifecycleConfiguration:
        Rules:
          - Id: DeleteAfter30DaysRule
            Prefix: delete-rule
            Status: Enabled
            ExpirationInDays: 30
  Outputs:
    BucketName:
      Value: !Ref S3BucketDataSet
      Description: